NUM := 1.pdf 2.pdf 3.pdf 4.pdf 5.pdf 6.pdf 7.pdf 8.pdf 9.pdf 10.pdf \
	11.pdf 12.pdf 13.pdf 14.pdf 15.pdf 16.pdf 17.pdf 18.pdf 19.pdf 20.pdf\
	21.pdf 22.pdf 23.pdf 24.pdf 25.pdf 26.pdf 27.pdf 28.pdf 29.pdf 30.pdf\
	31.pdf 32.pdf 33.pdf 34.pdf 35.pdf 36.pdf 37.pdf 38.pdf 39.pdf 40.pdf\
	41.pdf 42.pdf 43.pdf 44.pdf 45.pdf 46.pdf 47.pdf 48.pdf 49.pdf 50.pdf\
	u1.pdf 

all.pdf: $(NUM)
	pdftk {1..50}.pdf u1.pdf cat output all.pdf

1.pdf: 1 pre post body
	./make.sh 1 > /dev/null

2.pdf: 2 pre post body
	./make.sh 2 > /dev/null

3.pdf: 3 pre post body
	./make.sh 3 > /dev/null

4.pdf: 4 pre post body
	./make.sh 4 > /dev/null

5.pdf: 5 pre post body
	./make.sh 5 > /dev/null

6.pdf: 6 pre post body
	./make.sh 6 > /dev/null

7.pdf: 7 pre post body
	./make.sh 7 > /dev/null

8.pdf: 8 pre post body
	./make.sh 8 > /dev/null

9.pdf: 9 pre post body
	./make.sh 9 > /dev/null

10.pdf: 10 pre post body
	./make.sh 10 > /dev/null

11.pdf: 11 pre post body
	./make.sh 11 > /dev/null

12.pdf: 12 pre post body
	./make.sh 12 > /dev/null

13.pdf: 13 pre post body
	./make.sh 13 > /dev/null

14.pdf: 14 pre post body
	./make.sh 14 > /dev/null

15.pdf: 15 pre post body
	./make.sh 15 > /dev/null

16.pdf: 16 pre post body
	./make.sh 16 > /dev/null

17.pdf: 17 pre post body
	./make.sh 17 > /dev/null

18.pdf: 18 pre post body
	./make.sh 18 > /dev/null

19.pdf: 19 pre post body
	./make.sh 19 > /dev/null

20.pdf: 20 pre post body
	./make.sh 20 > /dev/null

21.pdf: 21 pre post body
	./make.sh 21 > /dev/null

22.pdf: 22 pre post body
	./make.sh 22 > /dev/null

23.pdf: 23 pre post body
	./make.sh 23 > /dev/null

24.pdf: 24 pre post body
	./make.sh 24 > /dev/null

25.pdf: 25 pre post body
	./make.sh 25 > /dev/null

26.pdf: 26 pre post body
	./make.sh 26 > /dev/null

27.pdf: 27 pre post body
	./make.sh 27 > /dev/null

28.pdf: 28 pre post body
	./make.sh 28 > /dev/null

29.pdf: 29 pre post body
	./make.sh 29 > /dev/null

30.pdf: 30 pre post body
	./make.sh 30 > /dev/null

31.pdf: 31 pre post body
	./make.sh 31 > /dev/null

32.pdf: 32 pre post body
	./make.sh 32 > /dev/null

33.pdf: 33 pre post body
	./make.sh 33 > /dev/null

34.pdf: 34 pre post body
	./make.sh 34 > /dev/null

35.pdf: 35 pre post body
	./make.sh 35 > /dev/null

36.pdf: 36 pre post body
	./make.sh 36 > /dev/null

37.pdf: 37 pre post body
	./make.sh 37 > /dev/null

38.pdf: 38 pre post body
	./make.sh 38 > /dev/null

39.pdf: 39 pre post body
	./make.sh 39 > /dev/null

40.pdf: 40 pre post body
	./make.sh 40 > /dev/null

41.pdf: 41 pre post body
	./make.sh 41 > /dev/null

42.pdf: 42 pre post body
	./make.sh 42 > /dev/null

43.pdf: 43 pre post body
	./make.sh 43 > /dev/null

44.pdf: 44 pre post body
	./make.sh 44 > /dev/null

45.pdf: 45 pre post body
	./make.sh 45 > /dev/null

46.pdf: 46 pre post body
	./make.sh 46 > /dev/null

47.pdf: 47 pre post body
	./make.sh 47 > /dev/null

48.pdf: 48 pre post body
	./make.sh 48 > /dev/null

49.pdf: 49 pre post body
	./make.sh 49 > /dev/null

50.pdf: 50 pre post body
	./make.sh 50 > /dev/null

u1.pdf: u1 pre post body
	./makemin.sh u1 > /dev/null
